name: Import Jupyter Notebooks as Blog Posts

on:
  push:
    branches: [main]
    #paths: ['notebooks/*.ipynb']
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  convert-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Jupyter and nbconvert
        run: pip install jupyter nbconvert

      - name: Convert notebooks to Hugo page bundles
        run: |
          mkdir -p content/post
          for file in notebooks/*.ipynb; do
            filename=$(basename "$file" .ipynb)
            output_dir="content/post/$filename"
            mkdir -p "$output_dir"
            jupyter nbconvert --to markdown "$file" --output "$filename" --output-dir "$output_dir"
            mv "$output_dir/$filename.md" "$output_dir/index.md"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto-import Jupyter notebooks
          title: Import Jupyter notebooks
          body: |
            This PR contains Markdown versions of notebooks.
          branch: auto/notebook-import
          delete-branch: true
          draft: false
          merge: true
          merge-method: squash
